### ISSUE TITLE
Addons folder in Downloads is not deleted at cleanup

### ISSUE THREAD

**Issue by Lesona-Systems** [Lesona-Systems/Underwolf#17]
The script is failing to cleanup the Addons folder created in Downloads on all platforms. Should switch to Python's tempfile/tempdir.

**Comment by Kshitijthegreat** [comment]
the default download folder is set to the OS default. I think forcing the user to input a download directory is a better way to avoid the possibility of errors.

**Comment by Lesona-Systems** [comment]
@Kshitijthegreat appreciate the insight! If main.py finds a user-provided download directory (that is already set in FF), it will perform all operations there. There is also a way to set the default download path with Selenium, but the issue shouldn't have anything to do with where we store the files, but how/when we're deleting them at cleanup. That should work regardless of download location, so there's a bug somewhere in clean_downloads().

**Comment by Lesona-Systems** [comment]
Turns out that clean_downloads() is written to only remove the zip files. Fix incoming.

**Comment by Lesona-Systems** [comment]
fixed by [[d8cee30](https://github.com/Lesona-Systems/Underwolf/commit/d8cee30833ae62bd1c90195b72dada4e0cf9da46)](https://github.com/Lesona-Systems/Underwolf/commit/d8cee30833ae62bd1c90195b72dada4e0cf9da46)
